// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZN52EOm8dafOP91NhF_hWgyIEWoevk8I',
    appId: '1:866448103051:web:f177d1fca04d0db37ea68e',
    messagingSenderId: '866448103051',
    projectId: 'shoppingapp-bcdb4',
    authDomain: 'shoppingapp-bcdb4.firebaseapp.com',
    storageBucket: 'shoppingapp-bcdb4.appspot.com',
    measurementId: 'G-GN8BX19V0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9raSsK5NW_U-wG5HnULPVv0tXMRwvKPc',
    appId: '1:866448103051:android:32991056ec2b373f7ea68e',
    messagingSenderId: '866448103051',
    projectId: 'shoppingapp-bcdb4',
    storageBucket: 'shoppingapp-bcdb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBsy2mu4z8-dzqvvDCyUTyB3jFjAukjI',
    appId: '1:866448103051:ios:71e1cc38028032fa7ea68e',
    messagingSenderId: '866448103051',
    projectId: 'shoppingapp-bcdb4',
    storageBucket: 'shoppingapp-bcdb4.appspot.com',
    iosClientId: '866448103051-sn6mvdffvebprfb24gb5tjrltjp4of19.apps.googleusercontent.com',
    iosBundleId: 'com.example.netshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcBsy2mu4z8-dzqvvDCyUTyB3jFjAukjI',
    appId: '1:866448103051:ios:71e1cc38028032fa7ea68e',
    messagingSenderId: '866448103051',
    projectId: 'shoppingapp-bcdb4',
    storageBucket: 'shoppingapp-bcdb4.appspot.com',
    iosClientId: '866448103051-sn6mvdffvebprfb24gb5tjrltjp4of19.apps.googleusercontent.com',
    iosBundleId: 'com.example.netshop',
  );
}
